spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/topaz_tree_db
    username: postgres
    password: qwerty0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
liquibase:
  enable: true

